# Generated by vmake version 10.3d

# Define path to each library
LIB_WORK = work

# Define path to each design unit
WORK__tb_gray = $(LIB_WORK)/_lib.qdb
WORK__tb = $(LIB_WORK)/_lib.qdb
WORK__mul = $(LIB_WORK)/_lib.qdb
WORK__datapath_gray = $(LIB_WORK)/_lib.qdb
WORK__add = $(LIB_WORK)/_lib.qdb
VCOM = vcom
VLOG = vlog
VOPT = vopt
SCCOM = sccom

whole_library : $(LIB_WORK)/_lib.qdb

$(LIB_WORK)/_lib.qdb : tb_gray.v mul.v datapath_gray.v add.v /home/timb/git/pma/tb_gray.v
	$(VLOG) -reportprogress 300 datapath_gray.v \
		 mul.v add.v tb_gray.v
	$(VLOG) -reportprogress 300 -L mtiAvm \
		 -L mtiOvm -L mtiUvm -L mtiUPF -L infact /home/timb/git/pma/tb_gray.v

